kind: ConfigMap
apiVersion: v1
metadata:
  name: akvo
  namespace: default
data:
  auth.url: https://akvotest.eu.auth0.com
  auth.public.client.id: D5LayiXP1pzq-6g2B_QVvzCw_eycZxQK
  auth.issuer.suffix.url: /
  auth.rsa.suffix.url: .well-known/jwks.json
  auth0.public.client.id: D5LayiXP1pzq-6g2B_QVvzCw_eycZxQK
  auth0.url: https://akvotest.eu.auth0.com
  email.host: mail.akvo.org
  environment: test
  flow.api.auth0.root: https://api-auth0.akvotest.org/flow
  flow.api.root: https://api-auth0.akvotest.org/flow
  keycloak.url: https://kc.akvotest.org/auth
  lumen.api.authz.probability: "0.5"
