kind: ConfigMap
apiVersion: v1
metadata:
  name: akvo
  namespace: default
data:
  auth.url: https://akvotest.eu.auth0.com/
  auth.public.client.id: D5LayiXP1pzq-6g2B_QVvzCw_eycZxQK
  auth.public.client.password: ucZCD5p-cYVPbwMGU6NrE8GVH_YLKFd8LKji7WADlgmhcehKa92k2CKL_CJti8JO
  auth.rsa.suffix.url: .well-known/jwks.json
  auth.end.session.endpoint.suffix: v2/logout
  email.host: mail.akvo.org
  environment: test
  flow.api.root: https://api-auth0.akvotest.org/flow
  keycloak.url: https://kc.akvotest.org/auth